name: StatsApp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pylint
  - pytest
  - pycodestyle
  - dash
  - pandas
  - scipy
  - statsmodels
  - waitress=3.0
  - werkseug=3.0
  - plots
  - plotly
  - numpy
  - pip
  - pip:
    - Flask
